### ISSUE TITLE
As a mummo I would like to get clear error messages so I dont do the errors twice

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#11]
_From @paavonelimarkka on November 4, 2014 8:10_

_Copied from original issue: N4SJAMK/teamboard-meta#178_

**Comment by tanelih** [comment]
A system has been implemented to allow for clear Error messages. Some of the more common error messages have been made into more human.

**Comment by narsuman** [comment]
Verified as obsolote
