### ISSUE TITLE
scrollable ei toimi safarilla? ainakaan member listingissa

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#116]

**Comment by Temetz** [comment]
Duplicate #126 #123

**Comment by melonmanchan** [comment]
Fixed in https://github.com/N4SJAMK/teamboard-client-react/pull/150

**Comment by narsuman** [comment]
Verified as Fixed 

Client version: v1.2.59
API version:    v0.4.25
IMG version:    v0.1.9
