### ISSUE TITLE
Cannot export large amount of tickets as image

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#118]

**Comment by httpsterio** [comment]
Bodyparser palauttaa 413, entity too large. Korjautuu varmaan nostamalla bodyparserin sallitun koon limittiä megaan? CSV minkä vein kun laudalla oli se tuhat tikettiä tms ja läjä kommentteja oli kooltaan vain 36kb

**Comment by narsuman** [comment]
Still

```
{
  "statusCode": 413,
  "error": "Request Entity Too Large",
  "message": "too many parameters"
}
```

Client version: v1.2.55
API version:    v0.4.24
IMG version:    v0.1.8

**Comment by narsuman** [comment]
{
  "statusCode": 413,
  "error": "Request Entity Too Large",
  "message": "too many parameters"
}

Client version: v1.2.56
API version:    v0.4.24
IMG version:    v0.1.8

![screenshot from 2015-07-10 09 06 31](https://cloud.githubusercontent.com/assets/8133582/8613208/cb83c850-26cb-11e5-9ff4-a4d40d0dc795.png)

**Comment by melonmanchan** [comment]
Should be fixed now

**Comment by narsuman** [comment]
Verified as Fixed !

Client version: v1.2.59
API version:    v0.4.25
IMG version:    v0.1.9
