### ISSUE TITLE
IE: näytössä on jokin pieni valkoinen loota..ei ole kuvassa kiinni kun liikkuu kyllä - mut ei pysty liikuttaa, liikkuu kartan mukana

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#119]
ei ole kuvassa kiinni kun liikkuu kyllä - mut ei pysty liikuttaa, liikkuu kartan mukana

Kyseessä IE selain

**Comment by httpsterio** [comment]
Tämä on tiketeissä olevien kommentien määrä. Virhe toistuu myös Windows Phonella, mutta ei Edge-selaimilla.

**Comment by Temetz** [comment]
Duplicate: #133

**Comment by narsuman** [comment]
Jiihaa!

Client version: v1.2.63
API version:    v0.4.25
IMG version:    v0.1.9
