### ISSUE TITLE
Help layer not working

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#121]
help-layerin sisältö on pääkäyttäjän painikkeille tehty, guest-käyttäjällä näkyy miten sattuu. Myöskään swipe ei toiminut mac book air:in trackpadillä

**Comment by httpsterio** [comment]
Koititteko trackpadilla painaa ja raahaa sivulle vai pyyhkäistä sivulle?

**Comment by narsuman** [comment]
Work with desktop.... and Macbook

**Comment by narsuman** [comment]
Verified as fixed

Client version: v1.2.70
API version:    v0.4.28
IMG version:    v0.1.9
