### ISSUE TITLE
Help-layer shows mambojambo..

### ISSUE THREAD

**Issue by HelSu** [N4SJAMK/teamboard-client-react#124]
help-layerin sisältö on pääkäyttäjän painikkeille tehty, guest-käyttäjällä näkyy miten sattuu. Myöskään swipe ei toiminut mac book air:in trackpadillä
- Selain Safari Version 8.0.6 (10600.6.3)
- Kone MacBook Air, OS X Yosemite Version 8.0.6 (10600.6.3)

**Comment by narsuman** [comment]
Näyttää toimivan nyt safarilla :) 

Client version: v1.2.68
API version:    v0.4.26
IMG version:    v0.1.9
