### ISSUE TITLE
Login with Opera

### ISSUE THREAD

**Issue by TommiHo** [N4SJAMK/teamboard-client-react#125]
Cant login to contriboard with Opera! 
![image](https://cloud.githubusercontent.com/assets/12408338/8592421/d6c041d8-2637-11e5-8cac-43cc4b04744f.png)

**Comment by Temetz** [comment]
Didnt get this error with normal usage. Was able to log in with Opera on Windows and Linux. Maybe this issue shows up when the API is experiencing a high load.

Next time it would be good to include the network log from the browser (CTRL+SHIFT+J).

**Comment by melonmanchan** [comment]
This works, yeah

**Comment by Paviaani** [comment]
Tested and working

Contriboard client: v1.2.66
API: v0.4.26
IO: v0.2.7
IMG: v0.1.9

Opera:
Version:    30.0.1835.88 - Opera is up to date
Update stream:  Stable
System: Ubuntu 14.04.2 LTS (x86_64; Unity)
