### ISSUE TITLE
Käyttäjävalikon scrolli ei toimi

### ISSUE THREAD

**Issue by HelSu** [N4SJAMK/teamboard-client-react#126]
käyttäjät valikkoa ei pysty scrollaamaan, ei näe kaikkia käyttäjiä

**Comment by melonmanchan** [comment]
Fixed in https://github.com/N4SJAMK/teamboard-client-react/pull/150

**Comment by narsuman** [comment]
Working now ! Verified as fixed

Client version: v1.2.59
API version:    v0.4.25
IMG version:    v0.1.9
