### ISSUE TITLE
kommenttien määrä tulee ulos puhekuplasta

### ISSUE THREAD

**Issue by HelSu** [N4SJAMK/teamboard-client-react#127]
kommenttien määrä ei näy ticketissä oikein, numerot tulee ulos puhekuplasta...

**Comment by Temetz** [comment]
We will show `99+` if we got over 100 comments on a ticket.

**Comment by narsuman** [comment]
Not working ?
Cannot see 99+ there is "10" after 104 comments..

Client version: v1.2.55
API version:    v0.4.24
IMG version:    v0.1.8

**Comment by melonmanchan** [comment]
Fixed in Client version: v1.2.56

**Comment by narsuman** [comment]
Client version: v1.2.56
API version:    v0.4.24
IMG version:    v0.1.8

Working now ok! Verified using Ubuntu + Chrome
