### ISSUE TITLE
Comment timestamps are showing wrong time

### ISSUE THREAD

**Issue by Temetz** [N4SJAMK/teamboard-client-react#131]
Seems that all comments are dated based on first comment posted.

**Comment by Temetz** [comment]
This is a API problem. Not related to client.

**Comment by narsuman** [comment]
![screenshot from 2015-07-10 08 47 36](https://cloud.githubusercontent.com/assets/8133582/8612994/2e73dc78-26c9-11e5-9e5c-8c4e29dea702.png)

**Comment by narsuman** [comment]
SUT Clocks are not syncronized ?

Client version: v1.2.56
API version:    v0.4.24
IMG version:    v0.1.8

**Comment by narsuman** [comment]
It will show  3 hours ? no minutes ?

**Comment by narsuman** [comment]
Cannot verify!

**Comment by Temetz** [comment]
At least its working for me on `sut-cb`

Client version: v1.2.56
API version:    v0.4.24
IMG version:    v0.1.9

**Comment by narsuman** [comment]
Now problem solved. My own machines clock  was set on local time.  It has to be set on  GMT 0 (Ubuntu )
Closed and obsolote.
