### ISSUE TITLE
Minimapin alue osoitin sekoittuu tikettien kanssa..  Vaikea navigoida.

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#138]
Z-indexi vaikka lappuja suuremmaksi.

**Comment by Temetz** [comment]
Fixed in: ffca2740f3b6ed8b19ddd6ed04858d1a8969fef7

**Comment by narsuman** [comment]
![screenshot from 2015-07-21 13 41 28](https://cloud.githubusercontent.com/assets/8133582/8798909/69601674-2fae-11e5-9ce2-f2d7039f57de.png)

Still quite difficult to locate where current view is ? Can we do something?

**Comment by narsuman** [comment]
Verified as fixed from Z value point of view :)

Client version  v1.2.86
API version v0.4.35
IMG version v0.1.10
