### ISSUE TITLE
Tickets blinking when cursor is on top of multiple tickets.

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#139]
Mikä selain ?

**Comment by tanelih** [comment]
I'm not sure if this is related to some z-index shenanigans? Maybe the ticket we bring forth doesn't have it's z-index set as high as it should be.

**Comment by narsuman** [comment]
closed now 

Client versio   v1.2.118
API versio  v0.4.42
IMG versio  v0.1.10
