### ISSUE TITLE
48: If you write a topic with scandic you will see some problems..

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#14]
_From @paavonelimarkka on September 25, 2014 7:22_

Problems with scandinavian keys..
If you write a topic with scandic you will see some problems...

Eg. Määrittelytehtävä 1

It will be shown on your own screen correctly, but another client will see MÄ¤.Ä¤rittelytehtÄ¤vÄ¤

This is a duplicate bug...

_Copied from original issue: N4SJAMK/teamboard-feedback#26_

**Comment by narsuman** [comment]
Still problems with new client ?

**Comment by tanelih** [comment]
This should be fixed with `utf8` module.

**Comment by narsuman** [comment]
Verified as fixed
