### ISSUE TITLE
Yhteys katkeaa puhelimella....

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#141]
Myöskin varmaan jotain mitä kannattaa pohtia: jos puhelimen heitän lukkoon hetkeksi (en osaa sanoa aikaa, sen aikaa ku edellinen viesti kesti kirjottaa), niin se heittää minut pihalle ja joutuisin taas kirjautumaan uusiks

**Comment by Temetz** [comment]
Puhelin taitaa mennä lukitustilassa sleep modeen jossa se tavallaan on "pois päältä". Tällöin myös datayhteydet ja täten myös socket yhteys kateaa joka varmaan aiheuttaa tuon uloskirjauksen.

**Comment by narsuman** [comment]
in future..
