### ISSUE TITLE
If I fast click create board and select that board I get Bad request error

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#146]
Im too fast, If I fast click create board and select that board I get Bad request error.

-2Fast4uJarmo

**Comment by narsuman** [comment]
Still exists? Moved from old feedback repo...

**Comment by Temetz** [comment]
I think this was fixed in 2584d71e73785156e76c75b77417dc08824aa471

**Comment by narsuman** [comment]
Verified as Fixed !

Client version: v1.2.62
API version:    v0.4.25
IMG version:    v0.1.9
