### ISSUE TITLE
Google+ needed for registration?

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#147]
Some problems..

Login process will ask me to join Google + when I am using my normal gmail account.
But If I change my account to an other one it will go smoothly through?

(I have normally four different gmail accounts in my broswer)

**Comment by narsuman** [comment]
![screenshot from 2015-07-10 08 13 30](https://cloud.githubusercontent.com/assets/8133582/8612719/9a2d7082-26c4-11e5-945a-870d4774f67f.png)

**Comment by Temetz** [comment]
We may be using too large scope on auth. We will be reviewing the required scope for our purposes.
https://developers.google.com/+/web/api/rest/oauth

**Comment by narsuman** [comment]
This is the first service which needs Google + activation :)

**Comment by AatuPitkanen** [comment]
This has been fixed and is ready to verify.

**Comment by narsuman** [comment]
Verified as fixed ;)

Client version: v1.2.58
API version:    v0.4.25
IMG version:    v0.1.9
