### ISSUE TITLE
You cannot see user names in online list if browser zoom is set 50 % 

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#148]
There is only icon visible? 

![screenshot from 2015-07-10 08 34 09](https://cloud.githubusercontent.com/assets/8133582/8612880/868497ec-26c7-11e5-97b6-094255bf0cac.png)

**Comment by JanKuukkanen** [comment]
Ready to verify

**Comment by narsuman** [comment]
Verified as fixed 

Client version: v1.2.71
API version:    v0.4.28
IMG version:    v0.1.9
