### ISSUE TITLE
IE and others: Bugs with help layer 

### ISSUE THREAD

**Issue by TommiHo** [N4SJAMK/teamboard-client-react#153]
X-button in Help layer is missing.
![image](https://cloud.githubusercontent.com/assets/12408338/8614596/c242c980-26f3-11e5-9be2-ab60896f2380.png)

**Comment by narsuman** [comment]
Seems to be fixed :) In IE 11 

Tested with JAMK Desktop

Client version: v1.2.70
API version:    v0.4.28
IMG version:    v0.1.9

**Comment by narsuman** [comment]
Still problem with Ubuntu Chrome
![screenshot from 2015-07-15 11 18 11](https://cloud.githubusercontent.com/assets/8133582/8693887/375d1048-2ae3-11e5-9302-78014130b390.png)

**Comment by mikkopoyhonen** [comment]
IE 11 and Ubuntu + Chrome Version 43.0.2357.134 seems to be ok. Still just a mess with mobile devices.

**Comment by nikolauska** [comment]
Tested on Ubuntu 14.04 with Chrome version 43.0.2357.134 (64-bit) and Firefox version 39.0 with no issues.
Is there any specific steps to reproduce this issue?

**Comment by tanelih** [comment]
This might be a CSS issue help layer button and the icon inside it. Have we made sure the vendor-prefixes are in places for the relevant attributes?

**Comment by narsuman** [comment]
Verified as fixed..

Client version  v1.2.86
API version v0.4.34
IMG version v0.1.10
