### ISSUE TITLE
79: When You are trying to create existing user account in registration you wont get error message..

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#16]
_From @paavonelimarkka on November 18, 2014 7:37_

When You are trying to create existing user account in registration you will get error message...

There should be a kind message "You have already registered, account is used etc.."

_Copied from original issue: N4SJAMK/teamboard-feedback#56_

**Comment by narsuman** [comment]
Need for checking? and fixing..

**Comment by tanelih** [comment]
Should be fixed in the latest!

**Comment by narsuman** [comment]
I tried to re-register narsuman@gmaail.com address and I I will get red dialog box "Register Failed!"

"Check your account ? / Are are you already registered etc?"

**Comment by narsuman** [comment]
Error message should be something else when trying to re-register ? "Please check you account!". 
There should be a button "Forgot your password" ? Implemented in future....

**Comment by tanelih** [comment]
There was a bug.

**Comment by narsuman** [comment]
Verified as fixed !
