### ISSUE TITLE
Online user counter shows also  non existing members 

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#161]
If users have left the board, counter will still show all members..
Non active users should removed from counter value...

**Comment by narsuman** [comment]
We should change counter to show all active members on the board

**Comment by narsuman** [comment]
Ensin verify :)

**Comment by tanelih** [comment]
I think the current plan is to show members active in the last 5 minutes.

**Comment by narsuman** [comment]
That's Ok !

**Comment by narsuman** [comment]
SUT shows zero users ? But dialog show one user just now...

Client version  v1.2.86
API version v0.4.34
IMG version v0.1.10

**Comment by tanelih** [comment]
Should be fixed now

**Comment by narsuman** [comment]
Counter values are not updated correctly. 

Client version v1.2.92
API version v0.4.35
IMG version v0.1.10

Eg. IE has value (7)  than Ubuntu firefox (5). After refresh both browsers have correct value..

Counter values is not decreased after logouts ?

![screenshot from 2015-07-22 08 41 20](https://cloud.githubusercontent.com/assets/8133582/8818709/5caf48ce-304d-11e5-8d77-98147c635ace.png)

Situation in Firefox (Ubuntu)

![ie-situation](https://cloud.githubusercontent.com/assets/8133582/8818731/a4353c12-304d-11e5-8e1d-7ff4a2c620ab.png)

Same time in IE

**Comment by narsuman** [comment]
I have now waited 4 min.. No changes..

If I login as a new guest in firefox (private mode) will member counter in IE browser added +1 !

**Comment by narsuman** [comment]
New member adding seems to be working ok!, but if member leaves a board counter is not decreased..

**Comment by tanelih** [comment]
Counter changed to show only active members.

**Comment by narsuman** [comment]
Seems to be fixed ! :)

Client version  v1.2.93
API version v0.4.35
IMG version v0.1.10
