### ISSUE TITLE
Long usernames on comments break the layout

### ISSUE THREAD

**Issue by Temetz** [N4SJAMK/teamboard-client-react#162]
![image](https://cloud.githubusercontent.com/assets/8721037/8647885/abdf024e-2964-11e5-879e-e4ae42b3fdc0.png)

**Comment by AatuPitkanen** [comment]
Ready to be verified.

**Comment by narsuman** [comment]
![screenshot from 2015-07-15 10 29 03](https://cloud.githubusercontent.com/assets/8133582/8693018/59706a24-2adc-11e5-81a0-5ac834bdafc4.png)

Still got a blues....

Ubuntu + Chrome 

Client version: v1.2.70
API version:    v0.4.28
IMG version:    v0.1.9

**Comment by Temetz** [comment]
How is this still broken? Seems okey to me.

**Comment by narsuman** [comment]
Comment text should be fully visible..

**Comment by narsuman** [comment]
Verified as fixed by Mikko

Client version: v1.2.70
API version:    v0.4.28
IMG version:    v0.1.9
