### ISSUE TITLE
Re-sharing board link leads to unknown area...

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#17]
I am logged as guest.. (using Chrome browser)
I copy link from browser window and paste link in Firefox
Now I try to open page..

I will see something odd..

**Comment by narsuman** [comment]
![screenshot from 2015-03-23 14 04 00](https://cloud.githubusercontent.com/assets/8133582/6779386/30c91af2-d164-11e4-939f-e1d3825a3d7b.png)

**Comment by narsuman** [comment]
If you are already logged in the Contriboard you will see situation above..
You have to be logged out and then you will find your self from login page....

**Comment by tanelih** [comment]
I think this is fixed in the latest release, at least I cannot reproduce it.

**Comment by narsuman** [comment]
Verified OK
