### ISSUE TITLE
Cannot set unknown key "createdBy" on Record, when moving a ticket.

### ISSUE THREAD

**Issue by Temetz** [N4SJAMK/teamboard-client-react#170]
![image](https://cloud.githubusercontent.com/assets/8721037/8717249/3dbc2f0e-2ba2-11e5-8deb-468abd0f885f.png)

**Comment by Temetz** [comment]
This also causes tickets not to sync between users.
Current workaround is to refresh the page.

**Comment by Temetz** [comment]
Fixed in: ea0a7d300c47beed1a504e3be20995311bacd907

**Comment by narsuman** [comment]
anything to do with this ? https://github.com/N4SJAMK/teamboard-client-react/issues/195

**Comment by narsuman** [comment]
Cannot Produce.  Fixed if no excuses ?

**Comment by narsuman** [comment]
closed now 

Client version  v1.2.92
API version v0.4.35
IMG version v0.1.10
