### ISSUE TITLE
After Guest logout I will get error message "Logout Failure" for a couple seconds

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#18]

**Comment by narsuman** [comment]
After logout
![screenshot from 2015-03-27 10 22 52](https://cloud.githubusercontent.com/assets/8133582/6864421/babdc228-d469-11e4-930a-29deabf9efac.png)

**Comment by tanelih** [comment]
This should be fixed in the latest build.

**Comment by narsuman** [comment]
Should be fixed and verified!
