### ISSUE TITLE
Background set should be changed

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#185]
Here you are: 

https://github.com/N4SJAMK/teamboard-meta/wiki/feature-default-background-set

**Comment by nikolauska** [comment]
This feature has been merged to master so it's ready to be verified

**Comment by narsuman** [comment]
YES !

Client version  v1.2.86
API version v0.4.35
IMG version v0.1.10

Images will be updated later and tested during (accepted)
