### ISSUE TITLE
User icon menu is not closing after clicking the board

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#188]
all dialogs should be closed if click on board ?

Client version  v1.2.86
API version v0.4.34
IMG version v0.1.10

**Comment by tanelih** [comment]
Do you mean the dropdown menu, which is opened by clicking on the user's avatar?

**Comment by narsuman** [comment]
Yes... All menus should be closed if board is clicked ?

**Comment by tanelih** [comment]
Yes

**Comment by santtusulander** [comment]
this should now be fixed.

**Comment by narsuman** [comment]
Verified as fixed! 

client: 1.2.98
api: 0.4.38
img: 0.1.10
io: 0.2.9

**Comment by narsuman** [comment]
Android tablet and phone browsers are not closing menu after board tap?
