### ISSUE TITLE
commenting in Chrome keep focus on text box (user can create multiple comments...)

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#189]
Focus should be moved off from text box after comment save..

Client version  v1.2.86
API version v0.4.34
IMG version v0.1.10

**Comment by narsuman** [comment]
Pressing enter in comment text box will close dialog.. Not good :)

Client version  v1.2.97
API version v0.4.37
IMG version v0.1.10

**Comment by AatuPitkanen** [comment]
This should be fixed now.

**Comment by narsuman** [comment]
Verified as fixed 23.7.2015 Klo 15:19

Client versio   latest
API versio  latest
IMG versio  latest
