### ISSUE TITLE
Without incoginto mode browser goes insane and take lot of processor time

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#19]
If you use incognito mode it will work ok!

**Comment by narsuman** [comment]
We found some ideas: My local storage (Chrome) was having a value  ""  for user object. Some how login process went in eternal loop...

There is something odd with registration etc..

**Comment by tanelih** [comment]
This should be fixed in the latest build. Accessing the user will now make sure the value is formatted properly.

**Comment by narsuman** [comment]
Verified as fixed

**Comment by narsuman** [comment]
Closed now
