### ISSUE TITLE
About box has Place Holder value..

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#190]
"About Description"

Client version  v1.2.86
API version v0.4.34
IMG version v0.1.10

**Comment by narsuman** [comment]
![2015-07-21 12 25 28](https://cloud.githubusercontent.com/assets/8133582/8797372/a7e1ff9e-2fa3-11e5-8108-0f73b92e89cd.jpg)

About box is also misaligned on older Chrome... Not needing fix..

**Comment by mikkopoyhonen** [comment]
![prkleitoimi](https://cloud.githubusercontent.com/assets/11857428/8798660/7d364c7e-2fac-11e5-832e-ef6e71c386cc.JPG) 

Also misaligned with smaller resolutions (1366 X 768) (Firefox)
