### ISSUE TITLE
IE edit dialog shows too much!

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#192]
![xqfwupx](https://cloud.githubusercontent.com/assets/8133582/8797755/3a7cf2ee-2fa6-11e5-90b2-7ce1a5da639e.png)

Client version  v1.2.86
API version v0.4.34
IMG version v0.1.10

**Comment by tanelih** [comment]
@melonmanchan check it out

**Comment by narsuman** [comment]
Verfied as fixed !

Client version  v1.2.93
API version v0.4.35
IMG version v0.1.10
