### ISSUE TITLE
Background size change is not updated in other clients?

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#194]
Client version  v1.2.86
API version v0.4.35
IMG version v0.1.10

I changed backgroud size from 10X10 to 99 X 99 in Chrome + Ubuntu

No update in Windows Chrome & IE

**Comment by nikolauska** [comment]
fixed on https://github.com/N4SJAMK/teamboard-api/commit/e20c295c5229e4296e9d3ac7a1374f29af413a57

**Comment by narsuman** [comment]
Verified as fixed

Client version  v1.2.97
API version v0.4.37
IMG version v0.1.10
