### ISSUE TITLE
Background is not updated in other clients..

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#195]
Client version  v1.2.86
API version v0.4.35
IMG version v0.1.10

I changed background (size 99x99) from default to game background... No change in Windows IE11 + Chrome

**Comment by narsuman** [comment]
Still got a problem !!

Client version  v1.2.93
API version v0.4.35
IMG version v0.1.10

**Comment by nikolauska** [comment]
fixed on https://github.com/N4SJAMK/teamboard-api/commit/e20c295c5229e4296e9d3ac7a1374f29af413a57

**Comment by narsuman** [comment]
Verified as fixed!

Client version  v1.2.97
API version v0.4.37
IMG version v0.1.10
