### ISSUE TITLE
Current board view area is hard to detect ? Can we enhance visibility?

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#196]
![screenshot from 2015-07-21 13 52 44](https://cloud.githubusercontent.com/assets/8133582/8799033/c72a0976-2faf-11e5-93d8-0ede6ba4451b.png)

Selected area in minimap is very hard to detect. We should have better visibility for selected area..

Could it be a possible to set more contrast for location indicator

**Comment by narsuman** [comment]
Current area is in left corner.. :)

**Comment by tanelih** [comment]
![gege](https://cloud.githubusercontent.com/assets/3582272/8848809/1784aa4a-3143-11e5-97bd-1080e3215cd1.jpg)
