### ISSUE TITLE
Double tap the board... text should be better visible or relocated ?

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#198]
Could be tune it little bit :)

Should text move according your location (if board is empty ?)!!

Image instead of text ?

**Comment by narsuman** [comment]
![screenshot from 2015-07-21 14 12 18](https://cloud.githubusercontent.com/assets/8133582/8799429/a4982bf6-2fb2-11e5-8e6a-11572186879c.png)

Text is not quite visible...

**Comment by nikolauska** [comment]
commit https://github.com/N4SJAMK/teamboard-client-react/commit/20701ee3f06582bf8accb9c71cf94ee21b64523d with tap image should fix this

**Comment by narsuman** [comment]
Verified as fixed!

Client version  v1.2.97
API version v0.4.37
IMG version v0.1.10
