### ISSUE TITLE
Please fix "use our own" item in background selector

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#199]
Should it be "Use your own background "

**Comment by narsuman** [comment]
[undefined | uploaded via ZenHub](https://files.zenhub.io/55ae2a9840305cf0075852f5)

**Comment by nikolauska** [comment]
Fixed https://github.com/N4SJAMK/teamboard-client-react/commit/372a7e3855522a62d6d4b5865335eabfdb89f632

**Comment by narsuman** [comment]
Verified as fixed!

Client versio   v1.2.91
API versio  v0.4.35
IMG versio  v0.1.10
