### ISSUE TITLE
When tab is pressed buttons need to be highlighted when active

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#2]
_From @spherelot on March 19, 2015 11:46_

This is a big issue when creating new ticket and tab is accidentally pressed. This results in that delete button is chosen and after that if space is pressed the ticket is deleted.

_Copied from original issue: N4SJAMK/teamboard-feedback#81_

**Comment by tanelih** [comment]
This is because the `dialog` component does not wrap its content inside a `form` element. We can do something similar to `components/dialog` what we did with `views/form`.

**Comment by tanelih** [comment]
I think this should be fixed by now?

**Comment by narsuman** [comment]
Still problems with IE and Firefox Chrome working ok. More visibility around selected item also ? Now its blue...

**Comment by narsuman** [comment]
Trello ticket created... new implementation...
