### ISSUE TITLE
175: Workshopissa kokeillaan ja tuli vastaan ongelma

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#20]
_From @n4sjamk-docker on April 17, 2015 10:3_

Moro

Workshopissa kokeillaan ja tuli vastaan ongelma.  Jos lapun kirjoittaminen kestää yli 10s joku timeout hävittää lapun ja sinne jo kirjoitetun.

Kikka-3 on kirjoittaa notepadiin ja sitten copy-paste. Onko muita kikkoja?

Ps. Selain of firefox

_Copied from original issue: N4SJAMK/teamboard-feedback#93_

**Comment by tanelih** [comment]
Olisikohan tämä ongelma johtunut siitä, että joku oli tuhonnut lapun sillä aikaa kun käyttäjä oli sitä kirjoittanut. On suunniteltu tulevaksi ominaisuudeksi sellaista joka ratkaisee tämän ongelman.

**Comment by narsuman** [comment]
joo!
