### ISSUE TITLE
Text does not fit the button on the ticket screen

### ISSUE THREAD

**Issue by JanKuukkanen** [N4SJAMK/teamboard-client-react#201]
![comment_button_style-error](https://cloud.githubusercontent.com/assets/12408621/8799578/c4d41a3c-2fb3-11e5-8c6c-b6ec2d1a2db3.png)

This affects most of the localisation options. Picture taken in virtualbox IE 11.

**Comment by nikolauska** [comment]
Fixed on https://github.com/N4SJAMK/teamboard-client-react/commit/abbb99093207424fb8a818c5e60adcc5b56b60ad

**Comment by narsuman** [comment]
Seems to be fixed enough !

Client version  v1.2.97
API version v0.4.37
IMG version v0.1.10
