### ISSUE TITLE
Ticket preview is complaining you have no tickets ?

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#202]
![screenshot from 2015-07-21 14 26 23](https://cloud.githubusercontent.com/assets/8133582/8799665/68893310-2fb4-11e5-99ba-60cbd4428cc6.png)

I have but only empty ones! 

Could it be ? "You are having nothing to show yet!"

**Comment by tanelih** [comment]
I don't think we should filter tickets on the fact that they are empty? Think it might just confuse users...
