### ISSUE TITLE
Avatar colors are wrong in comments

### ISSUE THREAD

**Issue by melonmanchan** [N4SJAMK/teamboard-client-react#204]
The background color of an avatarless user is always black (guest) on comments. It shows the right color for a second due to optimistic insertion of a new comment, but I guess the role is not transmitted properly through the events?

**Comment by melonmanchan** [comment]
![](http://i.imgur.com/IzBN65j.png)

**Comment by narsuman** [comment]
No close before verify!
 :)

**Comment by narsuman** [comment]
Verfied as fixed !

Client version  v1.2.91
API version v0.4.35
IMG version v0.1.10
