### ISSUE TITLE
Käyttäjälistassa ajanhetki ilmoitetaan oudosti

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#209]
![screenshot from 2015-07-22 08 35 36](https://cloud.githubusercontent.com/assets/8133582/8818633/9989f42a-304c-11e5-8b55-947a42ef2b1a.png)

"minuutteja ?" -> minuuttia

**Comment by mikkopoyhonen** [comment]
Sama siis myös kommenteissa

![screenshot from 2015-07-22 12 28 28](https://cloud.githubusercontent.com/assets/11857428/8822418/f24e7c72-306d-11e5-85ea-0eeb875b5933.png)

**Comment by nikolauska** [comment]
Not ready to verify as I have not yet created pull request to add fixes to master branch. 

Those fix messages just inform that I have pushed them to my fork and are ready to be added to master branch
