### ISSUE TITLE
Pikku typo kommenttejen aika-indikaattorissa

### ISSUE THREAD

**Issue by mikkopoyhonen** [N4SJAMK/teamboard-client-react#213]
![screenshot from 2015-07-22 12 28 28](https://cloud.githubusercontent.com/assets/11857428/8822335/5aec8c0c-306d-11e5-9ea3-03ce6704ca0c.png)

**Comment by narsuman** [comment]
Duplicate https://github.com/N4SJAMK/teamboard-client-react/issues/209
