### ISSUE TITLE
Duplicated tickets don't show headings in other browsers

### ISSUE THREAD

**Issue by JanKuukkanen** [N4SJAMK/teamboard-client-react#219]
![ticket_headings_issue](https://cloud.githubusercontent.com/assets/12408621/8844886/b25d8d82-3122-11e5-922f-7a48c687b015.png)

Probably related to issue #210

**Comment by JanKuukkanen** [comment]
Ready to verify

**Comment by narsuman** [comment]
Verified as fixed!

client: 1.2.98
api: 0.4.38
img: 0.1.10
io: 0.2.9
