### ISSUE TITLE
Bugs in translations

### ISSUE THREAD

**Issue by TommiHo** [N4SJAMK/teamboard-client-react#222]
There are a lot of bugs and typos.
![image](https://cloud.githubusercontent.com/assets/12408338/8845412/b04678e2-3127-11e5-975a-b9967a023b74.png)
![image](https://cloud.githubusercontent.com/assets/12408338/8845418/b3cf9b6a-3127-11e5-8754-cadea4711713.png)
![image](https://cloud.githubusercontent.com/assets/12408338/8845421/b7787818-3127-11e5-9119-4e5b28d49d12.png)
![image](https://cloud.githubusercontent.com/assets/12408338/8845424/ba0a09e8-3127-11e5-85e3-4e58b586205c.png)
![image](https://cloud.githubusercontent.com/assets/12408338/8845426/bd255754-3127-11e5-81f5-24eb8e192ba5.png)
![image](https://cloud.githubusercontent.com/assets/12408338/8845428/c0372486-3127-11e5-98d6-815c2aeec082.png)
![image](https://cloud.githubusercontent.com/assets/12408338/8845429/c3903e06-3127-11e5-99ad-68f017683408.png)
![image](https://cloud.githubusercontent.com/assets/12408338/8845436/c60746ca-3127-11e5-9daa-db235934f9d2.png)

**Comment by nikolauska** [comment]
Fixed in https://github.com/N4SJAMK/teamboard-client-react/commit/a4f09662e65242cf6735df860ac9ca3177652d01

**Comment by narsuman** [comment]
Verified as Fixed :)

WIN IE/FIREFOX + Ubuntu Chrome

Client version  v1.2.106
API version v0.4.39
IMG version v0.1.10
