### ISSUE TITLE
Board's users

### ISSUE THREAD

**Issue by TommiHo** [N4SJAMK/teamboard-client-react#230]
![image](https://cloud.githubusercontent.com/assets/12408338/8850167/5a82837a-314e-11e5-8c2e-38cc66268a8a.png)

There is also a bug with the cursor. It changes into "hover", when hovering "3 minuter sedan" like a link

**Comment by nikolauska** [comment]
#217

**Comment by narsuman** [comment]
Duplicate https://github.com/N4SJAMK/teamboard-client-react/issues/217
