### ISSUE TITLE
Preview mode shows moves on the background... Little bit confusing?

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#232]
Takes some efffort from browser.. Grey background for slide show ?

**Comment by tanelih** [comment]
We can create a separate View for the ReviewMode

**Comment by tanelih** [comment]
@santtusulander & @kuutamol will implement a separate `view/review`.

**Comment by narsuman** [comment]
Verfied as fixed ! OK

Client versio   v1.2.118
API versio  v0.4.42
IMG versio  v0.1.10
