### ISSUE TITLE
Preview should show only the tickets which have information content ?

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#233]
Now there is plenty of empty tickets ?

**Comment by tanelih** [comment]
Simple filter will do the trick

**Comment by nikolauska** [comment]
This issue now conflicts with https://github.com/N4SJAMK/teamboard-client-react/issues/202 so which one do we want?

**Comment by tanelih** [comment]
See #232... We will create a separate `ReviewView`, which will be its own page like `WorkspaceView` or `BoardView`...

**Comment by narsuman** [comment]
Verified as re-impleted an fixed

Client versio   v1.2.118
API versio  v0.4.42
IMG versio  v0.1.10
