### ISSUE TITLE
People editing stays permanently editing

### ISSUE THREAD

**Issue by ArttuIsopahkala** [N4SJAMK/teamboard-client-react#238]
on firefox. 
![11247877_10207376779047479_176696485_o](https://cloud.githubusercontent.com/assets/12408596/8871169/02779432-31fc-11e5-8457-5309b5c0c409.jpg)

**Comment by tanelih** [comment]
This happened on Safari as well...

**Comment by tanelih** [comment]
Some changes to how often events are sent were implemented... This means we should verify that this still happens...

**Comment by narsuman** [comment]
Seems to fixed OK

cannot reproduce

Client versio   v1.2.106
API versio  v0.4.39
IMG versio  v0.1.10
