### ISSUE TITLE
iPad issue: Board Members box is too short.

### ISSUE THREAD

**Issue by HelSu** [N4SJAMK/teamboard-client-react#240]
Board Members box is too short/small, shows only two first users (you have to scroll to see more).

////////CONTRIBOARD TESTING, 24.7.2015////////

Contriboard (SUT) versions:
Client version v1.2.100
API version v0.4.38
IMG version v0.1.10

Testing environment:
Flowdock -> Applen web-view

////////CONTRIBOARD TESTING, 24.7.2015////////

**Comment by Temetz** [comment]
Related issue #234

**Comment by tanelih** [comment]
Also related a bit to #241

**Comment by HelSu** [comment]
Still little bit too short but this will do for now.

**Comment by narsuman** [comment]
Client version  v1.2.128
API version v0.4.43
IMG version v0.1.10
