### ISSUE TITLE
iPad issue: cannot delete tickets if there is comments in tickets.

### ISSUE THREAD

**Issue by HelSu** [N4SJAMK/teamboard-client-react#241]
I cannot delete tickets if there is comments in ticket. Delete and clone buttons goes off the screen and i cannot scroll ticket. 

////////CONTRIBOARD TESTING, 24.7.2015////////

Contriboard (SUT) versions:
Client version v1.2.100
API version v0.4.38
IMG version v0.1.10

Testing environment:
Heli (1 kpl iPad iOS 8.3 (12F69) Flowdock -> Apple web-view)

////////CONTRIBOARD TESTING, 24.7.2015////////

**Comment by tanelih** [comment]
CSS!

**Comment by narsuman** [comment]
Verified as Fixed

Client version  v1.2.117
API version v0.4.42
IMG version v0.1.10
