### ISSUE TITLE
BOARD_PING event is send way too often

### ISSUE THREAD

**Issue by Temetz** [N4SJAMK/teamboard-client-react#243]
Sending `BOARD_PING` event every 2 seconds is quite often. I think we are fine even we only send it every 30 seconds or so. Just send one `BOARD_PING` when you join the board so the memberlist is up to date.

**Comment by tanelih** [comment]
Might be related to #249 and other real time issues

**Comment by Temetz** [comment]
It seems the ping is now send every 30 seconds. However the initial ping doesnt seem to work and board members list is empty until the "first" real board ping event is send.

`views/board.js:83`

**Comment by tanelih** [comment]
I'll make a @melonmanchan 'esque fix and put the initial event in some timeout because javascript.
