### ISSUE TITLE
NOTICE quest help dialog "bug"

### ISSUE THREAD

**Issue by F7347** [N4SJAMK/teamboard-client-react#246]
All the selections are not available for quests, so quest using help dialog will see "extra" tips.

![contribug](https://cloud.githubusercontent.com/assets/5491873/8871559/e6b0b604-31fe-11e5-9664-9da16ea150fa.png)

**Comment by tanelih** [comment]
Help layer should take the type of user into account...

**Comment by narsuman** [comment]
Closed now ! Implementation changed!

Client version  v1.2.129
API version v0.4.44
IMG version v0.1.10
