### ISSUE TITLE
iPad issue: Mini map square disappears off the minimap

### ISSUE THREAD

**Issue by HelSu** [N4SJAMK/teamboard-client-react#247]
Mini map square disappears off the minimap. (minimapilla neliö pääsee yli minimapin, siirtoneliö häviää yli laudan).

////////CONTRIBOARD TESTING, 24.7.2015////////

Contriboard (SUT) versions:
Client version v1.2.100
API version v0.4.38
IMG version v0.1.10

Testing environment:
Heli (1 kpl iPad iOS 8.3 (12F69) Flowdock -> Apple web-view)

////////CONTRIBOARD TESTING, 24.7.2015////////

**Comment by tanelih** [comment]
Can we get a screenshot?

**Comment by tanelih** [comment]
If the vertical area of the browser is small, minimap will be left behind the toolbar but the minimap cursor stays on top of the toolbar.

**Comment by Temetz** [comment]
z-index of minimap cursor and left side menu changed to fix this issue.
Minimap was also changed to right hand corner to better accommodate  devices with small screens.

Changes done in commit: https://github.com/N4SJAMK/teamboard-client-react/commit/7d4a1d6864e46f3f0f77c8aed0a95d7f17c9130e
_Client version:_ v.1.2.104

**Comment by narsuman** [comment]
Seems to be fixed!

Client version  v1.2.114
API version v0.4.41
IMG version v0.1.10
