### ISSUE TITLE
iPad issue: Ticket Snap does not work.

### ISSUE THREAD

**Issue by HelSu** [N4SJAMK/teamboard-client-react#248]
Snap to Grid does not work.

////////CONTRIBOARD TESTING, 24.7.2015////////

Contriboard (SUT) versions:
Client version v1.2.100
API version v0.4.38
IMG version v0.1.10

Testing environment:
Heli (1 kpl iPad iOS 8.3 (12F69) Flowdock -> Apple web-view)

////////CONTRIBOARD TESTING, 24.7.2015////////

**Comment by tanelih** [comment]
I've noticed some funky snap behaviour on both Chrome and Safari

**Comment by tanelih** [comment]
Cannot reproduce on said iPad? Might be related to some performance issues...

**Comment by narsuman** [comment]
Closed now 

Client versio   v1.2.118
API versio  v0.4.42
IMG versio  v0.1.10
