### ISSUE TITLE
iPad issue: Background images did not changed.

### ISSUE THREAD

**Issue by HelSu** [N4SJAMK/teamboard-client-react#249]
Background images did not changed when admin changed backgrounds (i'm guest).

////////CONTRIBOARD TESTING, 24.7.2015////////
Contriboard (SUT) versions:
Client version v1.2.100
API version v0.4.38
IMG version v0.1.10

Testing environment:
Heli (1 kpl iPad iOS 8.3 (12F69) Flowdock -> Apple web-view)
////////CONTRIBOARD TESTING, 24.7.2015////////

**Comment by tanelih** [comment]
Need to check if throttling the `user-activity` ping frequency to something like 30 seconds or more has any effect on some of the real time updates missing...

**Comment by AatuPitkanen** [comment]
Cannot reproduce, might be related to general API slowness with high loads.

**Comment by narsuman** [comment]
OK Closed now
