### ISSUE TITLE
As a guest I want to get info what happens when Admin deletes board.

### ISSUE THREAD

**Issue by HelSu** [N4SJAMK/teamboard-client-react#250]

**Comment by tanelih** [comment]
Currently all 404 ending requests are set to redirect the user to the workspace. We should probably add some sort of a "Resource not found" message along with explanation for normal users.

**Comment by nikolauska** [comment]
There is actually a message, but it disappears almost instantly when user is kicked out

**Comment by tanelih** [comment]
Change the redirect to happen with the `BOARD_REMOVE` event and otherwise just display some sort of an error message?

**Comment by narsuman** [comment]
There is message about deleted board. Acceted as fixed!

Client versio   v1.2.118
API versio  v0.4.42
IMG versio  v0.1.10
