### ISSUE TITLE
Original ticket not saved when duplicating ticket.

### ISSUE THREAD

**Issue by F7347** [N4SJAMK/teamboard-client-react#251]
Original ticket not saved when duplicating ticket. Bug appears when ticket is not saved once before duplicate

**Comment by tanelih** [comment]
I think this might actually be intended behavior?

**Comment by narsuman** [comment]
If there is content it would be nice if ticket is saved first ?

**Comment by narsuman** [comment]
Clone have to save the first ticket if there is no such already on the board (it's the first clone result )

**Comment by tanelih** [comment]
Can't be both a bug and enhancement at the same time...

**Comment by tanelih** [comment]
Feature not bug

**Comment by narsuman** [comment]
Closed now
