### ISSUE TITLE
Image in the ticket should act as a 'background' of sorts

### ISSUE THREAD

**Issue by tanelih** [N4SJAMK/teamboard-client-react#252]
When using markdown to add images to the ticket, the image stays the same size as in the source and doesn't scale to the ticket at all.

**Proposed solution**
Have `img` tags inside the ticket content scale to fill the ticket, similarly to board background.

**Comment by narsuman** [comment]
Picture is shown quite nice after pressing refresh ? 

Chrome + Ubuntu ?

**Comment by narsuman** [comment]
Working ok!

 Verified as fixed (Ubuntu  + Chrome + WIN IE11)

Client version  v1.2.106
API version v0.4.39
IMG version v0.1.10
