### ISSUE TITLE
iPad: Copying share board url does NOT work with Ipad

### ISSUE THREAD

**Issue by F7347** [N4SJAMK/teamboard-client-react#253]
does not work. Url cannot be copied, cannot be selected at all.

**Comment by tanelih** [comment]
![](https://archive.moe/download/r9k/image/1380/60/1380601608499.jpg)

**Comment by F7347** [comment]
With chrome it does NOT work, with safari it does work.

**Comment by tanelih** [comment]
On safari it works "somehow" (not good enough though). Verified as not working at all on Chrome.

**Comment by F7347** [comment]
Verified as fixed.
Client version  v1.2.106
API version v0.4.39
IMG version v0.1.10
