### ISSUE TITLE
iPad: Left side menu requires double clicking

### ISSUE THREAD

**Issue by Temetz** [N4SJAMK/teamboard-client-react#254]
If you want to edit the board, open minimap or any action from left menu, you are required to double click the menu. First click only selects the menu element.

**Comment by narsuman** [comment]
This was quite nasty to fix ?

**Comment by tanelih** [comment]
Do we use `HammerJS` for the toolbar items?

**Comment by tanelih** [comment]
The problem doesn't seem to be that big, at least in iOS safari? Occasionally the items will require double clicking but what doesn't when using mobile devices.
TL;DR We're using HammerJS tap events on the controls, done everything we can.

**Comment by narsuman** [comment]
Icons are too small for you fingers! Icons should have more "background" which makes it easier to activate. Janne K found this!

**Comment by Temetz** [comment]
Closing this as this is tagged with 'wontfix'
