### ISSUE TITLE
iPad: Creating ticket header with ipad

### ISSUE THREAD

**Issue by F7347** [N4SJAMK/teamboard-client-react#256]
If you write header and press "go" from keyboard; ticket is not saved. 

while writing content there is no "go" available to press.

Maybe the "go"-button should save the ticket.

**Comment by tanelih** [comment]
go

**Comment by narsuman** [comment]
Can we set text box editor to use common method ?

**Comment by tanelih** [comment]
This is probably because the content area is set to be a `textarea`, yet the heading is an `input`.
