### ISSUE TITLE
this.props.name is undefined error on commenting

### ISSUE THREAD

**Issue by melonmanchan** [N4SJAMK/teamboard-client-react#285]
http://i.imgur.com/BQPudTH.png

No idea how to reproduce 100%, just refreshed the site and attempted to make a comment

**Comment by tanelih** [comment]
I think this has something to do with the `Avatar` component and the `this.props.name` issues which are present also on #281 and #284

**Comment by narsuman** [comment]
Should be fixed!
Client version  v1.2.129
API version v0.4.44
IMG version v0.1.10
