### ISSUE TITLE
Clients not sending board:join event after socket is reconnected.

### ISSUE THREAD

**Issue by Temetz** [N4SJAMK/teamboard-client-react#31]
If the socket connection between _teamboard-client-react_ and _teamboard-io_ is lost and later regained the _teamboard-client-react_ isnt sending _socket.emit(JOIN_EVENT)_. 

This will cause that the client wont receive any updates made by other users.

**Comment by Temetz** [comment]
Pull request #30 should fix this issue.

**Comment by tanelih** [comment]
The pull request is now merged.
