### ISSUE TITLE
Triple clicking on board quickly causes an error

### ISSUE THREAD

**Issue by Temetz** [N4SJAMK/teamboard-client-react#39]
```
Uncaught TypeError: Cannot read property 'position' of null
```

![image](https://cloud.githubusercontent.com/assets/8721037/7806751/6dd00cac-038d-11e5-8a2c-01e640cc01b7.png)

**Comment by tanelih** [comment]
Sairaan nopee. 

![](http://i.ytimg.com/vi/OoyN8ykKTZU/hqdefault.jpg)
