### ISSUE TITLE
Dirty tickets can cause update requests

### ISSUE THREAD

**Issue by Temetz** [N4SJAMK/teamboard-client-react#40]
If there is server lag between the client and the server, the dirty ticket will be visible and user is able to go to ticket edit mode or try to move the dirty ticket. This will cause PUT requests to fail. The dirty ticket isnt removed from the board until the page is refreshed.

![image](https://cloud.githubusercontent.com/assets/8721037/7806899/d2ce29ee-038e-11e5-8543-6ce5dbc46ef0.png)

**Comment by tanelih** [comment]
I believe this issue should be discussed in the thread for #39.
