### ISSUE TITLE
User is able to enter a dirty board

### ISSUE THREAD

**Issue by Temetz** [N4SJAMK/teamboard-client-react#41]
If there is lag between the client and the server, user is able to enter a dirty board. This will cause all actions on the board fail.
#39 is a similar issue but with dirty tickets.

![image](https://cloud.githubusercontent.com/assets/8721037/7807003/3a64c152-0390-11e5-8406-1d374f9678e8.png)

**Comment by tanelih** [comment]
While having optimistic behaviour in the client is generally a good thing for user experience, it can cause issues such as these. For these sort of transitional things we might want to disable the optimistic behaviour simply by hand.

**Comment by tanelih** [comment]
I think this was fixed in #42
