### ISSUE TITLE
Ticket visible after first edit ?

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#58]
New ticket should be edited first by creator? After edit it will be visible to others

current creation flow should be changed ?

Proposed:
1. Double click board 
2. Ticket pops on the board 
3. Ticket is visible only for user until double click and edit?
## 
1. Double click board 
2. Ticket pops on the board 
3. It's visible but seems to be a "hot" for a 10 seconds.. So other users are not touching it ?
## 
1. Double click board 
2. Ticket pops on the board 
3. There is indication of user who has created a ticket and 

Something else?

**Comment by tanelih** [comment]
We can change the action emitted by double clicking on the board, from `createTicket`, which hits the API to just `addTicket`... This would also mean generating the dummy ID for the added ticket, and then checking before submitting the edit should the ticket be created or updated instead.

**Comment by narsuman** [comment]
Closed now new plans ahead...
