### ISSUE TITLE
Add board failure

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#6]
_From @Temetz on March 19, 2015 11:47_

Sometimes creating a board logs you out. After logging in there is a error message stuck on screen.

![image](https://cloud.githubusercontent.com/assets/8721037/6729758/4ad2c912-ce3e-11e4-93cd-a7011e7e267b.png)

![image](https://cloud.githubusercontent.com/assets/8721037/6729763/5ba95dfa-ce3e-11e4-8fea-95a9624c0121.png)

_Copied from original issue: N4SJAMK/teamboard-feedback#82_

**Comment by tanelih** [comment]
Measures have been taken, see #11.

**Comment by narsuman** [comment]
Cannot produce Verified as fixed..

**Comment by tanelih** [comment]
What?

**Comment by narsuman** [comment]
Closed now...
