### ISSUE TITLE
Huge amount of text in ticket slows down the site.

### ISSUE THREAD

**Issue by F7347** [N4SJAMK/teamboard-client-react#62]
Product: Contriboard
Build Version: v1.2.7
Description: If user writes too much text in to a ticket site slows down significantly
Reported By: Mikko Kemppinen

Steps:
1.Log in to Contriboard as an user
2.Enter to a board
3.Write a lot of text to a ticket
4. Site slows down very much

Expected result: Site should NOT slow down. Ticket text should be limited or solved some other way.

**Comment by tanelih** [comment]
Is this tested in PRODUCTION environment since that strips down a lot of the type checks etc.

**Comment by narsuman** [comment]
Working ok!

Client version: v1.2.62
API version:    v0.4.25
IMG version:    v0.1.9
