### ISSUE TITLE
Markdown text in ticket does not look right when ticket is minimized on board.

### ISSUE THREAD

**Issue by F7347** [N4SJAMK/teamboard-client-react#79]

**Comment by F7347** [comment]
Product: Contriboard
Build Version: v1.2.20
Description: Markdown text in ticket does not look right when ticket is minimized on board. For example: new lines disappears when closing the ticket.
Reported By: Mikko Kemppinen

Expected result: Markdown shows exactly the same when in ticket or on board.

**Comment by narsuman** [comment]
Moved to trello . closed now
